repos:
  - repo: local
    hooks:
      - id: python_format
        name: Python Format
        entry: uv run ruff format
        language: system
        types: [python]

      - id: python_lint
        name: Python Lint
        entry: uv run ruff check --fix
        language: system
        types: [python]
